#include QMK_KEYBOARD_H


/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

 enum{
    _BASE = 0, // base layer, more or less qwerty
    _NUM = 1, // numpad layer
    _FN = 2, // function layer
 };

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[_BASE] = LAYOUT(
        KC_GRV,  KC_1,    KC_2,    KC_3,     KC_4,    KC_5,   KC_6,             KC_7,  KC_8,   KC_9,    KC_0,     KC_MINS,  KC_EQL,   KC_BSPC, KC_MPLY,    KC_PSCR, KC_HOME, KC_MUTE, 
        KC_TAB,  KC_Q,    KC_W,    KC_E,     KC_R,    KC_T,                     KC_Y,  KC_U,   KC_I,    KC_O,     KC_P,     KC_LBRC,  KC_RBRC,             KC_INS,  KC_HOME, KC_PGUP, 
        KC_NO,   KC_A,    KC_S,    KC_D,     KC_F,    KC_G,                     KC_H,  KC_J,   KC_K,    KC_L,     KC_SCLN,  KC_QUOT,  KC_HASH, KC_ENT,     KC_DEL,  KC_END,  KC_PGDN, 
        KC_LSFT, KC_BSLS, KC_Z,    KC_X,     KC_C,    KC_V,   KC_B,             KC_B,  KC_N,   KC_M,    KC_COMM,  KC_DOT,   KC_SLSH,  KC_LSFT,             KC_MPRV, KC_UP,   KC_MNXT, 
        KC_LCTL, KC_LGUI, KC_LALT, MO(_NUM), MO(_FN), KC_NO,           KC_ESC,         KC_SPC,          KC_RALT,  KC_LGUI,  KC_MENU,  KC_LCTL,             KC_LEFT, KC_DOWN, KC_RGHT
    ),
	[_NUM] = LAYOUT(
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,          KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,    KC_P7,   KC_P8,   KC_P9, 
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,                   KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,             KC_P4,   KC_P5,   KC_P6, 
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,                   KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,    KC_P1,   KC_P2,   KC_P3, 
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,          KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,             KC_P0,   KC_PDOT, KC_PENT, 
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,          KC_TRNS,          KC_TRNS,          KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,             KC_TRNS, KC_TRNS, KC_TRNS
    ),
	[_FN] = LAYOUT(
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,          KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,    KC_TRNS, KC_TRNS, KC_TRNS, 
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,                   KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,             KC_TRNS, KC_TRNS, KC_TRNS, 
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,                   KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,    KC_TRNS, KC_TRNS, KC_TRNS, 
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,          KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,             KC_TRNS, KC_TRNS, KC_TRNS, 
        KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,          QK_BOOT,          KC_TRNS,          KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS)
};

const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][NUM_DIRECTIONS] = {
    [_BASE] = { ENCODER_CCW_CW(KC_VOLD, KC_VOLU) },  // default is volume
    [_NUM]  = { ENCODER_CCW_CW(KC_LEFT, KC_RIGHT) }, // in numpad layer we move the cursor
    [_FN]   = { ENCODER_CCW_CW(KC_MS_WH_UP, KC_MS_WH_DOWN) }, // in function layer we scroll up and down
};

#ifdef OLED_ENABLE
bool oled_task_user(void) {
    // Host Keyboard Layer Status
    oled_write_P(PSTR("Layer: "), false);

    switch (get_highest_layer(layer_state)) {
        case _BASE:
            oled_write_P(PSTR("BASE\n"), false);
            break;
        case _NUM:
            oled_write_P(PSTR("NUM\n"), false);
            break;
        case _FN:
            oled_write_P(PSTR("FN\n"), false);
            break;
        default:
            // Or use the write_ln shortcut over adding '\n' to the end of your string
            oled_write_ln_P(PSTR("?"), false);
    }
    
    return false;
}
#endif


